//! Verification suite — the executable form of the repo's self-application.
//!
//! Walks the checked-in canonical evidence tree (`frf/`, generated by
//! `./golden/demo.sh`) and re-derives every artifact using the tool's own
//! pure functions:
//!
//! - authority files still hash to their admitted `executable_sha256`;
//! - raw capture files hash to the values recorded in `capture.yaml`;
//! - residual raw hashes, token files, and κ output agree byte-for-byte;
//! - receipt ids are content-addressed (re-serializing a receipt must hash to
//!   the id's suffix), and every embedded residual/token re-derives;
//! - claim files are exactly what `positive_claim` compiles from their receipt.
//!
//! If a human hand-edited any generated artifact, this suite fails. That is
//! the point: generated facts must stay generated (Developer Checklist 23).
//!
//! Run: `cargo test --test verify_tree` (or `make verify`).

use frf::host;
use frf::kappa;
use frf::model::*;
use frf::sentences;
use frf::store::{is_valid_id, Store};
use std::fs;
use std::path::{Path, PathBuf};

fn store() -> Store {
    Store::new(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("frf"))
}

fn load<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    serde_yaml::from_str(&fs::read_to_string(path).unwrap())
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

fn hash_bytes(b: &[u8]) -> String {
    host::sha256_bytes(b)
}

fn hash_str(s: &str) -> String {
    hash_bytes(s.as_bytes())
}

fn repo_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel)
}

fn disposition_from_receipt(res: &ReceiptResidual) -> Disposition {
    match res.disposition.as_str() {
        "open" => {
            assert!(
                res.reason.is_none(),
                "open residual {} carries a reason",
                res.id
            );
            assert!(
                res.resolution_run_id.is_none(),
                "open residual {} carries a resolution_run_id",
                res.id
            );
            Disposition::Open
        }
        "fixed" => {
            let reason = res
                .reason
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without reason", res.id));
            let resolution_run_id = res
                .resolution_run_id
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without a resolution_run_id", res.id));
            Disposition::Fixed {
                reason,
                resolution_run_id,
            }
        }
        other => {
            let kind = ClosureKind::parse(other)
                .unwrap_or_else(|| panic!("unknown disposition '{other}' on {}", res.id));
            assert!(
                res.resolution_run_id.is_none(),
                "non-fixed residual {} carries a resolution_run_id",
                res.id
            );
            let reason = res
                .reason
                .clone()
                .unwrap_or_else(|| panic!("closed residual {} without reason", res.id));
            Disposition::Closed { kind, reason }
        }
    }
}

fn residual_fingerprint(r: &ResidualRecord) -> String {
    hash_str(&format!(
        "{}|{}|{}|{}",
        r.kind.as_str(),
        r.surface.as_deref().unwrap_or(""),
        r.raw_reference,
        r.raw_candidate
    ))
}

// ---------------------------------------------------------------------------
// authorities/
// ---------------------------------------------------------------------------

#[test]
fn authorities_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("authorities")).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
            continue;
        }
        let a: AuthorityRecord = load(&path);
        assert_eq!(a.schema_version, SCHEMA_AUTHORITY, "authority {}", a.id);
        assert_eq!(
            a.id,
            format!("{}-{}", a.name, a.version),
            "id must be name-version"
        );
        assert_eq!(
            a.kind, "executable_reference",
            "v0 admits only executable_reference"
        );
        assert!(is_valid_id(&a.id));
        assert!(a.platform.contains('-'), "platform format {a:?}");
        // The recorded file must still hash to the admitted value (no drift).
        let src = repo_path(&a.path);
        assert!(src.is_file(), "authority path {} missing", src.display());
        assert_eq!(
            host::sha256_file(&src).unwrap(),
            a.executable_sha256,
            "authority {} drifted from admission",
            a.id
        );
        found += 1;
    }
    assert!(found >= 1, "at least one authority must be admitted");
}

// ---------------------------------------------------------------------------
// captures/
// ---------------------------------------------------------------------------

#[test]
fn captures_are_self_consistent() {
    let store = store();
    let mut runs = 0;
    for entry in fs::read_dir(store.root.join("captures")).unwrap() {
        let run_dir = entry.unwrap().path();
        if !run_dir.is_dir() {
            continue;
        }
        let cap: CaptureManifest = load(&run_dir.join("capture.yaml"));
        assert_eq!(cap.schema_version, SCHEMA_CAPTURE);
        assert_eq!(cap.run, run_dir.file_name().unwrap().to_string_lossy());

        let fixture = repo_path(&cap.court_spec.fixture.path);
        assert!(fixture.is_file(), "fixture {} missing", fixture.display());
        assert_eq!(
            host::sha256_file(&fixture).unwrap(),
            cap.fixture_sha256,
            "fixture hash mismatch for run {}",
            cap.run
        );

        for (side, s) in [("reference", &cap.reference), ("candidate", &cap.candidate)] {
            let stdout = fs::read(run_dir.join(format!("{side}.stdout"))).unwrap();
            let stderr = fs::read(run_dir.join(format!("{side}.stderr"))).unwrap();
            assert_eq!(hash_bytes(&stdout), s.stdout_sha256, "{side} stdout hash");
            assert_eq!(hash_bytes(&stderr), s.stderr_sha256, "{side} stderr hash");
            assert_eq!(hash_str(&s.exit), s.exit_sha256, "{side} exit hash");
            assert_eq!(
                hash_str(&s.stderr_first_line),
                s.stderr_first_line_sha256,
                "{side} first-line hash"
            );
            let exit_txt = fs::read_to_string(run_dir.join(format!("{side}.exit.txt"))).unwrap();
            assert_eq!(exit_txt.trim(), s.exit, "{side} exit.txt");
            let stderr_text = String::from_utf8_lossy(&stderr);
            let first = stderr_text.split('\n').next().unwrap();
            assert_eq!(first, s.stderr_first_line, "{side} first line of stderr");
        }

        for id in &cap.residuals {
            assert!(
                store.residual_path(id).unwrap().is_file(),
                "run {} lists missing residual {id}",
                cap.run
            );
        }
        runs += 1;
    }
    assert!(runs >= 1, "at least one court run must be captured");
}

// ---------------------------------------------------------------------------
// residuals/ + tokens
// ---------------------------------------------------------------------------

#[test]
fn residuals_and_tokens_are_self_consistent() {
    let store = store();
    let mut count = 0;
    for entry in fs::read_dir(store.root.join("residuals")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        if name.ends_with(".token.yaml") || !name.ends_with(".yaml") {
            continue;
        }
        let r: ResidualRecord = load(&path);
        assert_eq!(r.schema_version, SCHEMA_RESIDUAL, "residual {}", r.id);
        assert_eq!(
            r.id,
            path.file_stem().unwrap().to_string_lossy(),
            "filename must match id"
        );
        assert!(
            r.id.starts_with(&format!("{}-{}", r.kind.domain_prefix(), r.kind.as_str())),
            "id shape for {}",
            r.id
        );
        match r.kind {
            ResidualKind::Exit => {
                assert_eq!(r.axis, Axis::Exit);
                assert_eq!(r.surface, None, "exit residual must not carry a surface");
            }
            ResidualKind::Text => {
                assert_eq!(r.axis, Axis::Stderr);
                assert_eq!(r.surface.as_deref(), Some("first-diagnostic-line"));
            }
        }
        assert_eq!(
            hash_str(&r.raw_reference),
            r.raw_reference_sha256,
            "raw_reference hash"
        );
        assert_eq!(
            hash_str(&r.raw_candidate),
            r.raw_candidate_sha256,
            "raw_candidate hash"
        );
        assert!(
            store.run_dir(&r.run).unwrap().is_dir(),
            "residual {} references missing run {}",
            r.id,
            r.run
        );
        match &r.disposition {
            Disposition::Open => assert!(r.disposition.reason().is_none()),
            Disposition::Closed { reason, .. } => {
                assert!(
                    !reason.trim().is_empty(),
                    "closed residual {} has empty reason",
                    r.id
                );
                assert!(
                    !reason.contains('\n'),
                    "closed residual {} has multi-line reason",
                    r.id
                );
            }
            Disposition::Fixed {
                reason,
                resolution_run_id,
            } => {
                assert!(
                    !reason.trim().is_empty() && !reason.contains('\n'),
                    "fixed residual {} has an invalid reason",
                    r.id
                );
                assert!(
                    !resolution_run_id.is_empty(),
                    "fixed residual {} lacks a resolution run",
                    r.id
                );
                // The resolution run must exist and must actually close the
                // residual: same court, axis now agreeing. A disposition is
                // not evidence; the run is.
                assert!(
                    store
                        .run_closes_axis(resolution_run_id, &r.court, r.axis)
                        .expect("resolution run must load and match court"),
                    "resolution run {resolution_run_id} does not close residual {}",
                    r.id
                );
            }
        }
        // The token file must be exactly κ(residual).
        let token: TokenRecord = load(&store.token_path(&r.id).unwrap());
        assert_eq!(token, kappa::kappa(&r), "token for {} drifted", r.id);
        count += 1;
    }
    assert!(count >= 2, "the golden path must leave two residuals");
}

// ---------------------------------------------------------------------------
// receipts/
// ---------------------------------------------------------------------------

#[test]
fn receipts_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("receipts")).unwrap() {
        let path = entry.unwrap().path();
        let id = path.file_stem().unwrap().to_string_lossy().to_string();
        let rec: Receipt = load(&path);
        assert_eq!(rec.schema_version, SCHEMA_RECEIPT, "receipt {id}");

        // The id is content-addressed: receipt-{run}-{sha8 of the body}.
        let rest = id
            .strip_prefix("receipt-")
            .unwrap_or_else(|| panic!("bad receipt id {id}"));
        let (run, hash8) = rest
            .rsplit_once('-')
            .expect("receipt id must end in -hash8");
        assert!(
            store.run_dir(run).unwrap().is_dir(),
            "receipt {id} references missing run {run}"
        );
        let yaml = store.to_yaml(&rec).unwrap();
        assert_eq!(
            &host::sha256_bytes(yaml.as_bytes())[..8],
            hash8,
            "receipt {id} is not content-addressed (hand-edited?)"
        );

        // Authority block matches the admitted record.
        let authority: AuthorityRecord = store
            .load_authority(&format!("{}-{}", rec.authority.name, rec.authority.version))
            .unwrap();
        assert_eq!(rec.authority.kind, authority.kind);
        assert_eq!(rec.authority.identity_hash, authority.executable_sha256);
        assert_eq!(
            rec.court.admissibility_envelope.authority_versions,
            vec![authority.version.clone()]
        );

        // Fixture block matches the run.
        let cap = store.load_capture(run).unwrap();
        assert_eq!(rec.fixtures.len(), 1);
        assert_eq!(rec.fixtures[0].id, cap.fixture);
        assert_eq!(rec.fixtures[0].hash, cap.fixture_sha256);
        assert_eq!(rec.fixtures[0].arguments, cap.arguments);

        // Observables are consistent with the residuals on each axis.
        let family = &rec.court.admissibility_envelope.fixture_family;
        for obs in &rec.observables {
            assert!(
                rec.court
                    .admissibility_envelope
                    .observables
                    .contains(&obs.axis),
                "undecared axis {} in receipt",
                obs.axis
            );
            let has_residual = rec.residuals.iter().any(|r| r.axis == obs.axis);
            match obs.verdict {
                ObservableVerdict::Pass => {
                    assert!(!has_residual, "pass verdict with residual on {}", obs.axis)
                }
                ObservableVerdict::Residual => assert!(
                    has_residual,
                    "residual verdict without residual on {}",
                    obs.axis
                ),
            }
            assert!(rec.residuals.iter().all(|r| r.axis != obs.axis || {
                let record = store.load_residual(&r.id).unwrap();
                let (ref_h, cand_h) = match record.axis {
                    Axis::Exit => (&cap.reference.exit_sha256, &cap.candidate.exit_sha256),
                    Axis::Stderr => (
                        &cap.reference.stderr_first_line_sha256,
                        &cap.candidate.stderr_first_line_sha256,
                    ),
                };
                obs.raw_reference_hash == *ref_h && obs.raw_candidate_hash == *cand_h
            }));
        }

        // Every residual entry re-derives from its file.
        for res in &rec.residuals {
            let record = store.load_residual(&res.id).unwrap();
            assert_eq!(res.axis, record.axis.as_str());
            assert_eq!(res.kind, record.kind);
            assert_eq!(res.raw_reference_hash, record.raw_reference_sha256);
            assert_eq!(res.raw_candidate_hash, record.raw_candidate_sha256);
            assert_eq!(
                res.grammar_state,
                kappa::grammar_state(&disposition_from_receipt(res)),
                "grammar_state for {}",
                res.id
            );
            assert_eq!(
                res.residual_fingerprint,
                residual_fingerprint(&record),
                "fingerprint for {}",
                res.id
            );
            assert_eq!(res.sign.norm, "single-run");
            assert_eq!(res.sign.drift, "not-observed");
            assert_eq!(res.sign.slew, "not-observed");
            assert_eq!(res.reproducer, rec.replay.command);
            assert!(res.invariant.is_empty(), "v0 has no invariants");
            if res.disposition == "fixed" {
                // Receipts are snapshots: the resolution edge is bound only
                // for entries that were fixed at emit time, and it must match
                // the residual file's.
                assert_eq!(
                    res.resolution_run_id,
                    record.disposition.resolution_run_id().map(str::to_string),
                    "resolution edge for {} drifted",
                    res.id
                );
            } else {
                assert!(
                    res.resolution_run_id.is_none(),
                    "non-fixed entry {} carries a resolution_run_id",
                    res.id
                );
            }
        }

        // Endoduction tokens re-derive from κ over the residual *as this
        // receipt saw it*: the raw fields from the file (immutable), the
        // disposition from the receipt (a snapshot, since receipts bind the
        // state at emit time).
        assert_eq!(rec.endoduction.schema_version, TOKEN_SCHEMA_VERSION);
        assert_eq!(rec.endoduction.tokens.len(), rec.residuals.len());
        for (res, token) in rec.residuals.iter().zip(&rec.endoduction.tokens) {
            let mut seen = store.load_residual(&res.id).unwrap();
            seen.disposition = disposition_from_receipt(res);
            let k = kappa::kappa(&seen);
            assert_eq!(token.residual_id, res.id);
            assert_eq!(token.token, k.token, "token for {}", res.id);
            assert_eq!(token.next_court, k.next_court);
            assert_eq!(token.blocks_claims, k.blocks_claims);
        }

        // Claim section is what the compiler would emit at this state.
        assert!(
            rec.claims.positive.is_empty(),
            "v0 receipts carry no positive claims"
        );
        assert_eq!(rec.claims.non_claims, sentences::non_claims(family));
        assert_eq!(
            rec.claims.blocked_by_open_residuals,
            sentences::refusal_lines_from_residuals(&rec.residuals, family)
        );
        found += 1;
    }
    assert!(
        found >= 2,
        "the golden path must leave two receipts (open + final)"
    );
}

// ---------------------------------------------------------------------------
// claims/
// ---------------------------------------------------------------------------

#[test]
fn claims_are_re_derivable_from_receipts() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("claims")).unwrap() {
        let path = entry.unwrap().path();
        let receipt_id = path.file_stem().unwrap().to_string_lossy().to_string();
        let claim: ClaimRecord = load(&path);
        assert_eq!(claim.schema_version, SCHEMA_CLAIM);
        assert_eq!(
            claim.receipt, receipt_id,
            "claim must reference its receipt"
        );

        let rec: Receipt = store.load_receipt(&receipt_id).unwrap();
        let family = &rec.court.admissibility_envelope.fixture_family;

        // A claim may only exist over a non-blocking receipt.
        assert!(
            sentences::refusal_lines(&rec).is_empty(),
            "claim {receipt_id} exists over a blocking receipt"
        );

        // Exactly one conservative sentence, byte-for-byte re-derivable.
        let expected = sentences::positive_claim(&rec).expect("claimable receipt");
        assert_eq!(
            claim.positive,
            vec![expected],
            "claim {receipt_id} drifted from its receipt"
        );
        assert_eq!(claim.non_claims, sentences::non_claims(family));
        assert_eq!(
            claim.authority,
            format!("{}-{}", rec.authority.name, rec.authority.version)
        );
        assert_eq!(claim.court, rec.court.id);
        assert_eq!(claim.fixture_family, *family);
        assert_eq!(
            claim.environment,
            format!(
                "{}-{} ({})",
                rec.environment.architecture,
                rec.environment.os,
                &rec.environment.environment_digest[..8]
            )
        );

        // The claimed receipt reflects the current residual dispositions.
        for res in &rec.residuals {
            let record = store.load_residual(&res.id).unwrap();
            assert_eq!(
                res.disposition,
                record.disposition.as_str(),
                "receipt {receipt_id} disposition for {} is stale",
                res.id
            );
        }
        found += 1;
    }
    assert!(found >= 1, "at least one compiled claim must exist");
}

// ---------------------------------------------------------------------------
// layout
// ---------------------------------------------------------------------------

#[test]
fn tree_mirrors_section_19_3() {
    let store = store();
    for sub in [
        "authorities",
        "courts",
        "captures",
        "residuals",
        "receipts",
        "claims",
    ] {
        assert!(
            store.root.join(sub).is_dir(),
            "missing {sub}/ in the evidence tree"
        );
    }
    assert!(store
        .root
        .join("courts/cli-malformed-input/manifest.yaml")
        .is_file());
    assert!(store
        .root
        .join("courts/cli-malformed-input/fixtures/malformed-path.conf")
        .is_file());
    // No stray non-YAML droppings in the generated directories.
    for sub in ["authorities", "receipts", "claims"] {
        for entry in fs::read_dir(store.root.join(sub)).unwrap() {
            let name = entry.unwrap().file_name().to_string_lossy().to_string();
            assert!(name.ends_with(".yaml"), "unexpected file {sub}/{name}");
        }
    }
}
