//! Verification suite — the executable form of the repo's self-application.
//!
//! Walks the checked-in canonical evidence tree (`frf/`, generated by
//! `./golden/demo.sh`) and re-derives every artifact using the tool's own
//! pure functions:
//!
//! - authority files still hash to their admitted `executable_sha256`;
//! - raw capture files hash to the values recorded in `capture.yaml`;
//! - residual raw hashes, token files, and κ output agree byte-for-byte;
//! - receipt ids are content-addressed (re-serializing a receipt must hash to
//!   the id's suffix), and every embedded residual/token re-derives;
//! - claim files are exactly what `positive_claim` compiles from their receipt.
//!
//! If a human hand-edited any generated artifact, this suite fails. That is
//! the point: generated facts must stay generated (Developer Checklist 23).
//!
//! Run: `cargo test --test verify_tree` (or `make verify`).

use frf::canon;
use frf::host;
use frf::kappa;
use frf::model::*;
use frf::sentences;
use frf::store::{is_valid_id, Store};
use std::fs;
use std::path::{Path, PathBuf};

fn store() -> Store {
    Store::new(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("frf"))
}

fn load<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    serde_yaml::from_str(&fs::read_to_string(path).unwrap())
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

/// Receipts are canonical JSON (RFC 8785); the other artifacts are YAML.
fn load_json<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    serde_json::from_str(&fs::read_to_string(path).unwrap())
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

fn hash_bytes(b: &[u8]) -> String {
    host::sha256_bytes(b)
}

fn hash_str(s: &str) -> String {
    hash_bytes(s.as_bytes())
}

fn repo_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel)
}

fn disposition_from_receipt(res: &ReceiptResidual) -> Disposition {
    match res.disposition.as_str() {
        "open" => {
            assert!(
                res.reason.is_none(),
                "open residual {} carries a reason",
                res.id
            );
            assert!(
                res.resolution_run_id.is_none(),
                "open residual {} carries a resolution_run_id",
                res.id
            );
            Disposition::Open
        }
        "fixed" => {
            let reason = res
                .reason
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without reason", res.id));
            let resolution_run_id = res
                .resolution_run_id
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without a resolution_run_id", res.id));
            let closure_predicate = res
                .closure_predicate
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without a closure_predicate", res.id));
            Disposition::Fixed {
                reason,
                resolution_run_id,
                closure_predicate,
            }
        }
        other => {
            let kind = ClosureKind::parse(other)
                .unwrap_or_else(|| panic!("unknown disposition '{other}' on {}", res.id));
            assert!(
                res.resolution_run_id.is_none() && res.closure_predicate.is_none(),
                "non-fixed residual {} carries a resolution_run_id or closure_predicate",
                res.id
            );
            let reason = res
                .reason
                .clone()
                .unwrap_or_else(|| panic!("closed residual {} without reason", res.id));
            Disposition::Closed { kind, reason }
        }
    }
}

fn residual_fingerprint(r: &ResidualRecord) -> String {
    frf::semantics::residual_fingerprint(r).unwrap()
}

// ---------------------------------------------------------------------------
// authorities/
// ---------------------------------------------------------------------------

#[test]
fn authorities_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("authorities")).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
            continue;
        }
        let a: AuthorityRecord = load(&path);
        assert_eq!(a.schema_version, SCHEMA_AUTHORITY, "authority {}", a.id);
        assert_eq!(
            a.id,
            format!("{}-{}", a.name, a.version),
            "id must be name-version"
        );
        assert_eq!(
            a.kind, "executable_reference",
            "v0 admits only executable_reference"
        );
        assert!(is_valid_id(&a.id));
        assert!(a.platform.contains('-'), "platform format {a:?}");
        // The recorded file must still hash to the admitted value (no drift).
        let src = repo_path(&a.path);
        assert!(src.is_file(), "authority path {} missing", src.display());
        assert_eq!(
            host::sha256_file(&src).unwrap(),
            a.executable_sha256,
            "authority {} drifted from admission",
            a.id
        );
        found += 1;
    }
    assert!(found >= 1, "at least one authority must be admitted");
}

// ---------------------------------------------------------------------------
// captures/
// ---------------------------------------------------------------------------

#[test]
fn captures_are_self_consistent() {
    let store = store();
    let mut runs = 0;
    for entry in fs::read_dir(store.root.join("captures")).unwrap() {
        let run_dir = entry.unwrap().path();
        if !run_dir.is_dir() {
            continue;
        }
        let cap: CaptureManifest = load(&run_dir.join("capture.yaml"));
        assert_eq!(cap.schema_version, SCHEMA_CAPTURE);
        assert_eq!(cap.run, run_dir.file_name().unwrap().to_string_lossy());

        // The tree is self-authenticating: the verified loader rederives the
        // run identity from the capture's own recorded fields (the same
        // function the court used), rehashes the raw side files, verifies the
        // content-addressed snapshots, and refuses any drift.
        frf::verify::load_capture_verified(&store, &cap.run)
            .unwrap_or_else(|e| panic!("capture {} fails verification: {e}", cap.run));

        // Provenance, bound at observation time: the environment is captured
        // structurally, comparator semantics re-derive from the registry, and
        // the runner + comparator implementations are recorded — two
        // questions answered separately: WHAT question (semantics) and WHO
        // asked it (provenance).
        assert_eq!(cap.environment.schema_version, SCHEMA_ENVIRONMENT);
        assert_eq!(cap.environment.os, std::env::consts::OS);
        assert_eq!(cap.environment.architecture, std::env::consts::ARCH);
        assert_eq!(cap.environment.digest.len(), 64);
        assert_eq!(
            cap.comparator_semantics.len(),
            cap.court_spec.admissibility_envelope.observables.len()
        );
        for c in &cap.comparator_semantics {
            assert_eq!(
                *c,
                frf::comparators::semantic(&c.id).unwrap(),
                "comparator semantics for {} must re-derive from the registry",
                c.id
            );
            assert!(
                cap.court_spec
                    .admissibility_envelope
                    .observables
                    .contains(&c.id),
                "comparator {} not declared",
                c.id
            );
        }
        assert_eq!(cap.provenance.schema_version, SCHEMA_PROVENANCE);
        assert_eq!(cap.provenance.runner.schema_version, SCHEMA_RUNNER);
        assert_eq!(cap.provenance.runner.frf_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(cap.provenance.runner.frf_executable_hash.len(), 64);
        assert_eq!(
            cap.provenance.comparator_implementations.len(),
            cap.comparator_semantics.len()
        );
        for c in &cap.provenance.comparator_implementations {
            assert_eq!(
                c.implementation_hash,
                cap.provenance.runner.frf_executable_hash
            );
            assert_eq!(c.runner_hash, cap.provenance.runner.frf_executable_hash);
            assert!(
                cap.court_spec
                    .admissibility_envelope
                    .observables
                    .contains(&c.id),
                "implementation {} not declared",
                c.id
            );
        }
        for artifact in [&cap.authority_artifact, &cap.candidate_artifact] {
            assert_eq!(artifact.sha256.len(), 64);
            let object = store.object_path(&artifact.sha256).unwrap();
            assert!(object.is_file(), "missing snapshot {}", object.display());
            assert_eq!(
                artifact.path,
                object.strip_prefix(&store.root).unwrap().to_string_lossy()
            );
            // Interpreter identity is present iff the snapshot is a script
            // with a shebang; the recorded interpreter path must be real.
            let bytes = fs::read(&object).unwrap();
            let has_shebang = bytes.starts_with(b"#!");
            match (&artifact.interpreter, has_shebang) {
                (Some(i), true) => {
                    assert_eq!(i.kernel_interpreter.sha256.len(), 64);
                    assert_eq!(i.downstream_interpreter.sha256.len(), 64);
                    assert!(
                        Path::new(&i.kernel_interpreter.path).is_file(),
                        "kernel interpreter {} missing",
                        i.kernel_interpreter.path
                    );
                    assert!(
                        Path::new(&i.downstream_interpreter.path).is_file(),
                        "downstream interpreter {} missing",
                        i.downstream_interpreter.path
                    );
                    // An env shebang records the resolver; a plain shebang
                    // records no resolver and kernel == downstream.
                    match &i.resolver {
                        Some(r) => {
                            assert_eq!(r.kind, "env");
                            assert_eq!(r.path, i.kernel_interpreter.path);
                            assert_eq!(r.path_digest.len(), 64);
                        }
                        None => assert_eq!(
                            i.kernel_interpreter, i.downstream_interpreter,
                            "non-env shebang: kernel must BE the interpreter"
                        ),
                    }
                }
                (None, false) => {}
                (Some(_), false) => panic!("interpreter recorded for a non-script artifact"),
                (None, true) => panic!("script artifact without interpreter identity"),
            }
        }
        assert_eq!(cap.authority_artifact.sha256.len(), 64);
        // The admitted authority is exactly the artifact that ran.
        let admitted: AuthorityRecord = store.load_authority(&cap.authority).unwrap();
        assert_eq!(cap.authority_artifact.sha256, admitted.executable_sha256);
        // The semantic identity re-derives from the captured declaration:
        // authority ARTIFACT bytes + comparator SEMANTICS, no implementation
        // identity.
        assert_eq!(
            frf::semantics::court_semantic_identity(
                &cap.court_spec,
                &cap.authority_artifact.sha256,
                &cap.fixture_sha256,
                &cap.comparator_semantics
            )
            .unwrap(),
            cap.court_semantic_identity
        );

        let fixture = repo_path(&cap.court_spec.fixture.path);
        assert!(fixture.is_file(), "fixture {} missing", fixture.display());
        assert_eq!(
            host::sha256_file(&fixture).unwrap(),
            cap.fixture_sha256,
            "fixture hash mismatch for run {}",
            cap.run
        );

        for (side, s) in [("reference", &cap.reference), ("candidate", &cap.candidate)] {
            let stdout = fs::read(run_dir.join(format!("{side}.stdout"))).unwrap();
            let stderr = fs::read(run_dir.join(format!("{side}.stderr"))).unwrap();
            assert_eq!(hash_bytes(&stdout), s.stdout_sha256, "{side} stdout hash");
            assert_eq!(hash_bytes(&stderr), s.stderr_sha256, "{side} stderr hash");
            assert_eq!(hash_str(&s.exit), s.exit_sha256, "{side} exit hash");
            assert_eq!(
                hash_str(&s.stderr_first_line),
                s.stderr_first_line_sha256,
                "{side} first-line hash"
            );
            let exit_txt = fs::read_to_string(run_dir.join(format!("{side}.exit.txt"))).unwrap();
            assert_eq!(exit_txt.trim(), s.exit, "{side} exit.txt");
            let stderr_text = String::from_utf8_lossy(&stderr);
            let first = stderr_text.split('\n').next().unwrap();
            assert_eq!(first, s.stderr_first_line, "{side} first line of stderr");
            let stdout_text = String::from_utf8_lossy(&stdout);
            let first_out = stdout_text.split('\n').next().unwrap();
            assert_eq!(
                first_out, s.stdout_first_line,
                "{side} first line of stdout"
            );
            let out_first_txt =
                fs::read_to_string(run_dir.join(format!("{side}.stdout_first_line.txt"))).unwrap();
            assert_eq!(
                out_first_txt.trim(),
                s.stdout_first_line,
                "{side} stdout_first_line.txt"
            );
            assert_eq!(
                hash_str(&s.stdout_first_line),
                s.stdout_first_line_sha256,
                "{side} stdout first-line hash"
            );
        }

        for id in &cap.residuals {
            assert!(
                store.residual_path(id).unwrap().is_file(),
                "run {} lists missing residual {id}",
                cap.run
            );
        }
        runs += 1;
    }
    assert!(runs >= 1, "at least one court run must be captured");
}

// ---------------------------------------------------------------------------
// objects/ — content-addressed execution snapshots
// ---------------------------------------------------------------------------

#[test]
fn objects_are_content_addressed_and_sealed() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("objects/sha256")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        assert_eq!(name.len(), 64, "object name {name}");
        assert!(name.chars().all(|c| c.is_ascii_hexdigit()));
        // The name MUST be the content: a hand-planted or corrupted object
        // fails here, and the court runner refuses to execute it.
        let bytes = fs::read(&path).unwrap();
        assert_eq!(
            host::sha256_bytes(&bytes),
            name,
            "object {} is not content-addressed (hand-edited?)",
            path.display()
        );
        // (Sealing is a materialization-time property, unit-tested in
        // store.rs: git does not preserve write bits across checkouts, so a
        // cloned tree's modes are not evidence.)
        found += 1;
    }
    assert!(
        found >= 3,
        "the golden path must leave at least three objects (authority, candidate, fixture)"
    );
}

// ---------------------------------------------------------------------------
// residuals/ + tokens
// ---------------------------------------------------------------------------

#[test]
fn residuals_and_tokens_are_self_consistent() {
    let store = store();
    let mut count = 0;
    for entry in fs::read_dir(store.root.join("residuals")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        if name.ends_with(".token.yaml") || !name.ends_with(".yaml") {
            continue;
        }
        let r: ResidualRecord = load(&path);
        assert_eq!(r.schema_version, SCHEMA_RESIDUAL, "residual {}", r.id);
        assert_eq!(
            r.id,
            path.file_stem().unwrap().to_string_lossy(),
            "filename must match id"
        );
        assert!(
            r.id.starts_with(&format!("{}-{}", r.kind.domain_prefix(), r.kind.as_str())),
            "id shape for {}",
            r.id
        );
        match r.kind {
            ResidualKind::Exit => {
                assert_eq!(r.axis, Axis::Exit);
                assert_eq!(r.surface, None, "exit residual must not carry a surface");
            }
            ResidualKind::Text => {
                assert!(
                    matches!(r.axis, Axis::Stderr | Axis::Stdout),
                    "text residual on unexpected axis {:?}",
                    r.axis
                );
                assert_eq!(
                    r.surface.as_deref(),
                    match r.axis {
                        Axis::Stderr => Some("first-diagnostic-line"),
                        Axis::Stdout => Some("first-stdout-line"),
                        Axis::Exit => unreachable!(),
                    },
                    "surface must match the axis"
                );
            }
        }
        assert_eq!(
            hash_str(&r.raw_reference),
            r.raw_reference_sha256,
            "raw_reference hash"
        );
        assert_eq!(
            hash_str(&r.raw_candidate),
            r.raw_candidate_sha256,
            "raw_candidate hash"
        );
        assert!(
            store.run_dir(&r.run).unwrap().is_dir(),
            "residual {} references missing run {}",
            r.id,
            r.run
        );
        // The observation is bound to the exact candidate artifact that ran.
        let capture = store.load_capture(&r.run).unwrap();
        assert_eq!(
            r.candidate_sha256, capture.candidate_artifact.sha256,
            "residual {} candidate identity must match its run",
            r.id
        );
        // The observation record must never carry a disposition.
        let raw_yaml = fs::read_to_string(&path).unwrap();
        assert!(
            !raw_yaml.contains("disposition"),
            "observation {} must be immutable (no disposition field)",
            r.id
        );
        // Dispositions live in append-only events; the projection is the
        // last event, and the token follows it.
        let events = store.disposition_events(&r.id).unwrap();
        let disposition = events
            .last()
            .map(|e| e.disposition.clone())
            .unwrap_or(Disposition::Open);
        match &disposition {
            Disposition::Open => assert!(disposition.reason().is_none()),
            Disposition::Closed { reason, .. } => {
                assert!(
                    !reason.trim().is_empty(),
                    "closed residual {} has empty reason",
                    r.id
                );
                assert!(
                    !reason.contains('\n'),
                    "closed residual {} has multi-line reason",
                    r.id
                );
            }
            Disposition::Fixed {
                reason,
                resolution_run_id,
                closure_predicate,
            } => {
                assert!(
                    !reason.trim().is_empty() && !reason.contains('\n'),
                    "fixed residual {} has an invalid reason",
                    r.id
                );
                assert!(
                    !resolution_run_id.is_empty(),
                    "fixed residual {} lacks a resolution run",
                    r.id
                );
                assert!(
                    !closure_predicate.is_empty(),
                    "fixed residual {} lacks a closure predicate",
                    r.id
                );
                // The resolution run must rerun the same question under a
                // compatible envelope and actually close the residual.
                store
                    .resolution_compatibility(&r.run, resolution_run_id, r.axis)
                    .expect("resolution run must satisfy the comparability predicate");
            }
        }
        // Event sequence numbers are dense and start at 0001.
        for (i, e) in events.iter().enumerate() {
            assert_eq!(
                e.residual_id, r.id,
                "event {i} of {} has a mismatched residual_id",
                r.id
            );
            assert!(
                e.disposition.as_str() != "open",
                "event {i} of {} is 'open' — events are closures only",
                r.id
            );
        }
        // The token file must be exactly κ(residual, projection).
        let token: TokenRecord = load(&store.token_path(&r.id).unwrap());
        assert_eq!(
            token,
            kappa::kappa(&r, &disposition),
            "token for {} drifted",
            r.id
        );
        count += 1;
    }
    assert!(count >= 2, "the golden path must leave two residuals");
}

// ---------------------------------------------------------------------------
// receipts/
// ---------------------------------------------------------------------------

#[test]
fn receipts_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("receipts")).unwrap() {
        let path = entry.unwrap().path();
        let id = path.file_stem().unwrap().to_string_lossy().to_string();
        let rec: Receipt = load_json(&path);
        assert_eq!(rec.schema_version, SCHEMA_RECEIPT, "receipt {id}");

        // Evidentiary verification: the receipt must be content-addressed,
        // semantically conformant, and derived from its verified capture
        // (court, artifacts, environment, provenance, comparators,
        // observables, residuals, fingerprints, tokens, dispositions,
        // resolution edges) before the tree will treat it as evidence.
        frf::verify::load_receipt_verified(&store, &id)
            .unwrap_or_else(|e| panic!("receipt {id} fails verification: {e}"));

        // The id is content-addressed: receipt-{run}-{full SHA-256 of the
        // canonical (RFC 8785) body bytes}.
        let rest = id
            .strip_prefix("receipt-")
            .unwrap_or_else(|| panic!("bad receipt id {id}"));
        let (run, digest) = rest
            .rsplit_once('-')
            .expect("receipt id must end in the digest");
        assert_eq!(
            digest.len(),
            64,
            "the digest is the full SHA-256, not a prefix"
        );
        assert_eq!(rec.run, run, "receipt {id} run field must match its id");
        assert!(
            store.run_dir(run).unwrap().is_dir(),
            "receipt {id} references missing run {run}"
        );
        let json = canon::canonical(&rec).unwrap();
        assert_eq!(
            host::sha256_bytes(json.as_bytes()),
            digest,
            "receipt {id} is not content-addressed (hand-edited?)"
        );

        // Structured replay block: executing it reproduces the run.
        assert_eq!(rec.replay.program, "frf");
        assert_eq!(rec.replay.expected_run_identity, rec.run);
        assert!(rec.replay.argv.len() >= 5);
        assert_eq!(rec.replay.argv[0], "--root");
        assert_eq!(
            rec.replay.argv[1], "frf",
            "evidence root recorded at capture"
        );
        assert_eq!(rec.replay.argv[2], "court");
        assert_eq!(rec.replay.argv[3], "run");

        // Authority block matches the admitted record.
        let authority: AuthorityRecord = store
            .load_authority(&format!("{}-{}", rec.authority.name, rec.authority.version))
            .unwrap();
        assert_eq!(rec.authority.kind, authority.kind);
        assert_eq!(rec.authority.identity_hash, authority.executable_sha256);
        assert_eq!(
            rec.court.admissibility_envelope.authority_versions,
            vec![authority.version.clone()]
        );

        // Fixture block matches the run.
        let cap = store.load_capture(run).unwrap();
        assert_eq!(rec.fixtures.len(), 1);
        assert_eq!(rec.fixtures[0].id, cap.fixture);
        assert_eq!(rec.fixtures[0].hash, cap.fixture_sha256);
        assert_eq!(rec.fixtures[0].arguments, cap.arguments);
        assert_eq!(
            rec.fixtures[0].declared_arguments, cap.court_spec.fixture.arguments,
            "the declared arguments are the semantic identity's input"
        );

        // Runner + comparator semantics + environment are copied from the
        // capture (bound at observation time), never reconstructed at emit
        // time.
        assert_eq!(rec.provenance, cap.provenance);
        assert_eq!(rec.comparator_semantics, cap.comparator_semantics);
        assert_eq!(rec.environment, cap.environment);
        assert_eq!(rec.court.semantic_identity, cap.court_semantic_identity);
        assert_eq!(
            rec.authority.interpreter,
            cap.authority_artifact.interpreter
        );
        assert_eq!(rec.candidate.identity_hash, cap.candidate_artifact.sha256);
        assert_eq!(
            rec.candidate.interpreter,
            cap.candidate_artifact.interpreter
        );

        // Observables are consistent with the residuals on each axis.
        let family = &rec.court.admissibility_envelope.fixture_family;
        for obs in &rec.observables {
            assert!(
                rec.court
                    .admissibility_envelope
                    .observables
                    .contains(&obs.axis),
                "undecared axis {} in receipt",
                obs.axis
            );
            let has_residual = rec.residuals.iter().any(|r| r.axis == obs.axis);
            match obs.verdict {
                ObservableVerdict::Pass => {
                    assert!(!has_residual, "pass verdict with residual on {}", obs.axis)
                }
                ObservableVerdict::Residual => assert!(
                    has_residual,
                    "residual verdict without residual on {}",
                    obs.axis
                ),
            }
            assert!(rec.residuals.iter().all(|r| r.axis != obs.axis || {
                let record = store.load_residual(&r.id).unwrap();
                let (ref_h, cand_h) = match record.axis {
                    Axis::Exit => (&cap.reference.exit_sha256, &cap.candidate.exit_sha256),
                    Axis::Stderr => (
                        &cap.reference.stderr_first_line_sha256,
                        &cap.candidate.stderr_first_line_sha256,
                    ),
                    Axis::Stdout => (
                        &cap.reference.stdout_first_line_sha256,
                        &cap.candidate.stdout_first_line_sha256,
                    ),
                };
                obs.raw_reference_hash == *ref_h && obs.raw_candidate_hash == *cand_h
            }));
        }

        // Every residual entry re-derives from its file.
        for res in &rec.residuals {
            let record = store.load_residual(&res.id).unwrap();
            assert_eq!(res.axis, record.axis.as_str());
            assert_eq!(res.kind, record.kind);
            assert_eq!(res.raw_reference_hash, record.raw_reference_sha256);
            assert_eq!(res.raw_candidate_hash, record.raw_candidate_sha256);
            assert_eq!(
                res.grammar_state,
                kappa::grammar_state(&disposition_from_receipt(res)),
                "grammar_state for {}",
                res.id
            );
            assert_eq!(
                res.residual_fingerprint,
                residual_fingerprint(&record),
                "fingerprint for {}",
                res.id
            );
            assert_eq!(res.sign.norm, "single-run");
            assert_eq!(res.sign.drift, "not-observed");
            assert_eq!(res.sign.slew, "not-observed");
            // A residual reproduces by replaying the run that observed it.
            assert_eq!(res.reproducer, rec.run);
            assert!(res.invariant.is_empty(), "v0 has no invariants");
            if res.disposition == "fixed" {
                // Receipts are snapshots: the resolution edge is bound only
                // for entries that were fixed at emit time, and it must match
                // the projected disposition (the last event).
                let projected = store.current_disposition(&res.id).unwrap();
                assert_eq!(
                    res.resolution_run_id,
                    projected.resolution_run_id().map(str::to_string),
                    "resolution edge for {} drifted",
                    res.id
                );
                assert_eq!(
                    res.closure_predicate.as_deref(),
                    match &projected {
                        Disposition::Fixed {
                            closure_predicate, ..
                        } => Some(closure_predicate.as_str()),
                        _ => None,
                    },
                    "closure predicate for {} drifted",
                    res.id
                );
            } else {
                assert!(
                    res.resolution_run_id.is_none() && res.closure_predicate.is_none(),
                    "non-fixed entry {} carries a resolution_run_id or closure_predicate",
                    res.id
                );
            }
        }

        // Endoduction tokens re-derive from κ over the residual *as this
        // receipt saw it*: the raw fields from the file (immutable), the
        // disposition from the receipt (a snapshot, since receipts bind the
        // state at emit time).
        assert_eq!(rec.endoduction.schema_version, TOKEN_SCHEMA_VERSION);
        assert_eq!(rec.endoduction.tokens.len(), rec.residuals.len());
        for (res, token) in rec.residuals.iter().zip(&rec.endoduction.tokens) {
            let seen = store.load_residual(&res.id).unwrap();
            let disposition = disposition_from_receipt(res);
            let k = kappa::kappa(&seen, &disposition);
            assert_eq!(token.residual_id, res.id);
            assert_eq!(token.token, k.token, "token for {}", res.id);
            assert_eq!(token.next_court, k.next_court);
            assert_eq!(token.blocks_claims, k.blocks_claims);
        }

        // Claim section is what the compiler would emit at this state.
        assert!(
            rec.claims.positive.is_empty(),
            "v0 receipts carry no positive claims"
        );
        assert_eq!(rec.claims.non_claims, sentences::non_claims(family));
        assert_eq!(
            rec.claims.blocked_by_open_residuals,
            sentences::refusal_lines_from_residuals(&rec.residuals, family)
        );
        found += 1;
    }
    assert!(
        found >= 2,
        "the golden path must leave two receipts (open + final)"
    );
}

// ---------------------------------------------------------------------------
// claims/
// ---------------------------------------------------------------------------

#[test]
fn claims_are_re_derivable_from_receipts() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("claims")).unwrap() {
        let path = entry.unwrap().path();
        let receipt_id = path.file_stem().unwrap().to_string_lossy().to_string();
        let claim: ClaimRecord = load(&path);
        assert_eq!(claim.schema_version, SCHEMA_CLAIM);
        assert_eq!(
            claim.receipt, receipt_id,
            "claim must reference its receipt"
        );

        let verified = frf::verify::load_receipt_verified(&store, &receipt_id)
            .unwrap_or_else(|e| panic!("claim {receipt_id}: receipt fails verification: {e}"));
        let rec = verified.body();
        let family = &rec.court.admissibility_envelope.fixture_family;

        // A claim may only exist over a receipt whose run's evidence is not
        // invalidated by harness (run-level). Open/unknown residuals block
        // only their own axis, so a scoped claim can coexist with them.
        assert!(
            sentences::harness_refusal_lines(&rec.residuals, family).is_empty(),
            "claim {receipt_id} exists over a harness-invalidated run"
        );

        // Exactly one conservative sentence, byte-for-byte re-derivable.
        let expected = sentences::positive_claim(rec).expect("claimable receipt");
        assert_eq!(
            claim.positive,
            vec![expected],
            "claim {receipt_id} drifted from its receipt"
        );
        // Claim IR re-derives: the observable scope is the axes THIS run
        // observed passing; the exclusions are the residuals on other axes.
        let expected_scope: Vec<String> = rec
            .observables
            .iter()
            .filter(|obs| !rec.residuals.iter().any(|r| r.axis == obs.axis))
            .map(|obs| obs.axis.clone())
            .collect();
        assert_eq!(claim.observable_scope, expected_scope);
        let expected_excluded: Vec<String> = rec.residuals.iter().map(|r| r.id.clone()).collect();
        assert_eq!(claim.excluded_residuals, expected_excluded);
        // A claim never covers an axis with a residual on it.
        assert!(claim
            .observable_scope
            .iter()
            .all(|axis| !rec.residuals.iter().any(|r| r.axis == *axis)));
        assert_eq!(claim.non_claims, sentences::non_claims(family));
        assert_eq!(
            claim.authority,
            format!("{}-{}", rec.authority.name, rec.authority.version)
        );
        assert_eq!(claim.court, rec.court.id);
        assert_eq!(claim.fixture_family, *family);
        assert_eq!(
            claim.environment,
            format!(
                "{}-{} ({})",
                rec.environment.architecture,
                rec.environment.os,
                &rec.environment.digest[..8]
            )
        );

        // The claimed receipt reflects the current residual dispositions.
        for res in &rec.residuals {
            let projected = store.current_disposition(&res.id).unwrap();
            assert_eq!(
                res.disposition,
                projected.as_str(),
                "receipt {receipt_id} disposition for {} is stale",
                res.id
            );
        }

        // The claim is attributed to the EXACT candidate artifact the
        // receipt's run executed: the identity hash must equal the run's
        // captured candidate bytes, never a label.
        let rest = receipt_id
            .strip_prefix("receipt-")
            .unwrap_or_else(|| panic!("bad receipt id {receipt_id}"));
        let (run, _) = rest
            .rsplit_once('-')
            .expect("receipt id must end in the digest");
        let cap = store.load_capture(run).unwrap();
        assert_eq!(
            claim.candidate.identity_hash, cap.candidate_artifact.sha256,
            "claim {receipt_id} is attributed to a candidate artifact the run did not execute"
        );
        found += 1;
    }
    assert!(found >= 1, "at least one compiled claim must exist");
}

// ---------------------------------------------------------------------------
// layout
// ---------------------------------------------------------------------------

#[test]
fn tree_mirrors_section_19_3() {
    let store = store();
    for sub in [
        "authorities",
        "courts",
        "captures",
        "objects",
        "residuals",
        "receipts",
        "claims",
    ] {
        assert!(
            store.root.join(sub).is_dir(),
            "missing {sub}/ in the evidence tree"
        );
    }
    assert!(store
        .root
        .join("courts/cli-malformed-input/manifest.yaml")
        .is_file());
    assert!(store
        .root
        .join("courts/cli-malformed-input/fixtures/malformed-path.conf")
        .is_file());
    // No stray non-YAML droppings in the generated directories; receipts are
    // canonical JSON, everything else is YAML.
    for sub in ["authorities", "receipts", "claims"] {
        for entry in fs::read_dir(store.root.join(sub)).unwrap() {
            let name = entry.unwrap().file_name().to_string_lossy().to_string();
            let ok = if sub == "receipts" {
                name.ends_with(".json")
            } else {
                name.ends_with(".yaml")
            };
            assert!(ok, "unexpected file {sub}/{name}");
        }
    }
}
