//! Verification suite — the executable form of the repo's self-application.
//!
//! Walks the checked-in canonical evidence tree (`frf/`, generated by
//! `./golden/demo.sh`) and re-derives every artifact using the tool's own
//! pure functions:
//!
//! - authority files still hash to their admitted `executable_sha256`;
//! - raw capture files hash to the values recorded in `capture.json`;
//! - residual raw hashes, token files, and κ output agree byte-for-byte;
//! - receipt ids are content-addressed (re-serializing a receipt must hash to
//!   the id's suffix), and every embedded residual/token re-derives;
//! - claim files are exactly what `positive_claim` compiles from their receipt.
//!
//! If a human hand-edited any generated artifact, this suite fails. That is
//! the point: generated facts must stay generated (Developer Checklist 23).
//!
//! Run: `cargo test --test verify_tree` (or `make verify`).

use frf::canon;
use frf::host;
use frf::kappa;
use frf::model::*;
use frf::sentences;
use frf::store::{is_valid_id, Store};
use std::fs;
use std::path::{Path, PathBuf};

fn store() -> Store {
    Store::new(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("frf"))
}

fn load<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    serde_json::from_str(&fs::read_to_string(path).unwrap())
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

/// Receipts are canonical JSON (RFC 8785); the other artifacts are YAML.
fn load_json<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    serde_json::from_str(&fs::read_to_string(path).unwrap())
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

fn hash_bytes(b: &[u8]) -> String {
    host::sha256_bytes(b)
}

fn hash_str(s: &str) -> String {
    hash_bytes(s.as_bytes())
}

fn repo_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel)
}

fn disposition_from_receipt(res: &ReceiptResidual) -> Disposition {
    match res.disposition.as_str() {
        "open" => {
            assert!(
                res.reason.is_none(),
                "open residual {} carries a reason",
                res.id
            );
            assert!(
                res.resolution_run_id.is_none(),
                "open residual {} carries a resolution_run_id",
                res.id
            );
            Disposition::Open
        }
        "fixed" => {
            let reason = res
                .reason
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without reason", res.id));
            let resolution_run_id = res
                .resolution_run_id
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without a resolution_run_id", res.id));
            let closure_predicate = res
                .closure_predicate
                .clone()
                .unwrap_or_else(|| panic!("fixed residual {} without a closure_predicate", res.id));
            Disposition::Fixed {
                reason,
                resolution_run_id,
                closure_predicate,
            }
        }
        other => {
            let kind = ClosureKind::parse(other)
                .unwrap_or_else(|| panic!("unknown disposition '{other}' on {}", res.id));
            assert!(
                res.resolution_run_id.is_none() && res.closure_predicate.is_none(),
                "non-fixed residual {} carries a resolution_run_id or closure_predicate",
                res.id
            );
            let reason = res
                .reason
                .clone()
                .unwrap_or_else(|| panic!("closed residual {} without reason", res.id));
            Disposition::Closed { kind, reason }
        }
    }
}

fn residual_fingerprint(r: &ResidualRecord) -> String {
    frf::semantics::residual_fingerprint(r).unwrap()
}

// ---------------------------------------------------------------------------
// authorities/
// ---------------------------------------------------------------------------

#[test]
fn authorities_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("authorities")).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let a: AuthorityRecord = load(&path);
        assert_eq!(a.schema_version, SCHEMA_AUTHORITY, "authority {}", a.id);
        assert_eq!(
            a.id,
            format!("{}-{}", a.name, a.version),
            "id must be name-version"
        );
        assert_eq!(
            a.kind, "executable_reference",
            "v0 admits only executable_reference"
        );
        assert!(is_valid_id(&a.id));
        assert!(a.platform.contains('-'), "platform format {a:?}");
        // The recorded file must still hash to the admitted value (no drift).
        let src = repo_path(&a.path);
        assert!(src.is_file(), "authority path {} missing", src.display());
        assert_eq!(
            host::sha256_file(&src).unwrap(),
            a.executable_sha256,
            "authority {} drifted from admission",
            a.id
        );
        found += 1;
    }
    assert!(found >= 1, "at least one authority must be admitted");
}

// ---------------------------------------------------------------------------
// captures/
// ---------------------------------------------------------------------------

#[test]
fn captures_are_self_consistent() {
    let store = store();
    let mut runs = 0;
    for entry in fs::read_dir(store.root.join("captures")).unwrap() {
        let run_dir = entry.unwrap().path();
        if !run_dir.is_dir() {
            continue;
        }
        let cap: CaptureManifest = load(&run_dir.join("capture.json"));
        assert_eq!(cap.schema_version, SCHEMA_CAPTURE);
        assert_eq!(cap.run, run_dir.file_name().unwrap().to_string_lossy());

        // The tree is self-authenticating: the verified loader rederives the
        // run identity from the capture's own recorded fields (the same
        // function the court used), rehashes the raw side files, verifies the
        // content-addressed snapshots, and refuses any drift.
        frf::verify::load_capture_verified(&store, &cap.run)
            .unwrap_or_else(|e| panic!("capture {} fails verification: {e}", cap.run));

        // Provenance, bound at observation time: the environment is captured
        // structurally, comparator semantics re-derive from the registry, and
        // the runner + comparator implementations are recorded — two
        // questions answered separately: WHAT question (semantics) and WHO
        // asked it (provenance).
        assert_eq!(cap.environment.schema_version, SCHEMA_ENVIRONMENT);
        assert_eq!(cap.environment.os, std::env::consts::OS);
        assert_eq!(cap.environment.architecture, std::env::consts::ARCH);
        assert_eq!(cap.environment.digest.len(), 64);
        assert_eq!(
            cap.comparator_semantics.len(),
            cap.court_spec.admissibility_envelope.observables.len()
        );
        for c in &cap.comparator_semantics {
            assert_eq!(
                *c,
                frf::comparators::semantic(&c.id).unwrap(),
                "comparator semantics for {} must re-derive from the registry",
                c.id
            );
            assert!(
                cap.court_spec
                    .admissibility_envelope
                    .observables
                    .contains(&c.id),
                "comparator {} not declared",
                c.id
            );
        }
        assert_eq!(cap.provenance.schema_version, SCHEMA_PROVENANCE);
        assert_eq!(cap.provenance.runner.schema_version, SCHEMA_RUNNER);
        assert_eq!(cap.provenance.runner.frf_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(cap.provenance.runner.frf_executable_hash.len(), 64);
        assert_eq!(
            cap.provenance.comparator_implementations.len(),
            cap.comparator_semantics.len()
        );
        for c in &cap.provenance.comparator_implementations {
            assert_eq!(
                c.implementation_hash,
                cap.provenance.runner.frf_executable_hash
            );
            assert_eq!(c.runner_hash, cap.provenance.runner.frf_executable_hash);
            assert!(
                cap.court_spec
                    .admissibility_envelope
                    .observables
                    .contains(&c.id),
                "implementation {} not declared",
                c.id
            );
        }
        for artifact in [&cap.authority_artifact, &cap.candidate_artifact] {
            assert_eq!(artifact.sha256.len(), 64);
            let object = store.object_path(&artifact.sha256).unwrap();
            assert!(object.is_file(), "missing snapshot {}", object.display());
            assert_eq!(
                artifact.path,
                object.strip_prefix(&store.root).unwrap().to_string_lossy()
            );
            // Interpreter identity is present iff the snapshot is a script
            // with a shebang; the recorded interpreter path must be real.
            let bytes = fs::read(&object).unwrap();
            let has_shebang = bytes.starts_with(b"#!");
            match (&artifact.interpreter, has_shebang) {
                (Some(i), true) => {
                    assert_eq!(i.kernel_interpreter.sha256.len(), 64);
                    assert_eq!(i.downstream_interpreter.sha256.len(), 64);
                    assert!(
                        Path::new(&i.kernel_interpreter.path).is_file(),
                        "kernel interpreter {} missing",
                        i.kernel_interpreter.path
                    );
                    assert!(
                        Path::new(&i.downstream_interpreter.path).is_file(),
                        "downstream interpreter {} missing",
                        i.downstream_interpreter.path
                    );
                    // An env shebang records the resolver; a plain shebang
                    // records no resolver and kernel == downstream.
                    match &i.resolver {
                        Some(r) => {
                            assert_eq!(r.kind, "env");
                            assert_eq!(r.path, i.kernel_interpreter.path);
                            assert_eq!(r.path_digest.len(), 64);
                        }
                        None => assert_eq!(
                            i.kernel_interpreter, i.downstream_interpreter,
                            "non-env shebang: kernel must BE the interpreter"
                        ),
                    }
                }
                (None, false) => {}
                (Some(_), false) => panic!("interpreter recorded for a non-script artifact"),
                (None, true) => panic!("script artifact without interpreter identity"),
            }
        }
        assert_eq!(cap.authority_artifact.sha256.len(), 64);
        // The admitted authority is exactly the artifact that ran.
        let admitted: AuthorityRecord = store.load_authority(&cap.authority).unwrap();
        assert_eq!(cap.authority_artifact.sha256, admitted.executable_sha256);
        // The semantic identity re-derives from the captured declaration:
        // authority ARTIFACT bytes + comparator SEMANTICS, no implementation
        // identity.
        assert_eq!(
            frf::semantics::court_semantic_identity(
                &cap.court_spec,
                &cap.authority_artifact.sha256,
                &cap.fixture_sha256,
                &cap.comparator_semantics,
                &cap.normalizer_semantics,
                &cap.adapter_semantics,
            )
            .unwrap(),
            cap.court_semantic_identity
        );

        let fixture = repo_path(&cap.court_spec.fixture.path);
        assert!(fixture.is_file(), "fixture {} missing", fixture.display());
        assert_eq!(
            host::sha256_file(&fixture).unwrap(),
            cap.fixture_sha256,
            "fixture hash mismatch for run {}",
            cap.run
        );

        for (side, s) in [("reference", &cap.reference), ("candidate", &cap.candidate)] {
            let stdout = fs::read(run_dir.join(format!("{side}.stdout"))).unwrap();
            let stderr = fs::read(run_dir.join(format!("{side}.stderr"))).unwrap();
            assert_eq!(hash_bytes(&stdout), s.stdout_sha256, "{side} stdout hash");
            assert_eq!(hash_bytes(&stderr), s.stderr_sha256, "{side} stderr hash");
            assert_eq!(hash_str(&s.exit), s.exit_sha256, "{side} exit hash");
            assert_eq!(
                hash_str(&s.stderr_first_line),
                s.stderr_first_line_sha256,
                "{side} first-line hash"
            );
            let exit_txt = fs::read_to_string(run_dir.join(format!("{side}.exit.txt"))).unwrap();
            assert_eq!(exit_txt.trim(), s.exit, "{side} exit.txt");
            let stderr_text = String::from_utf8_lossy(&stderr);
            let first = stderr_text.split('\n').next().unwrap();
            assert_eq!(first, s.stderr_first_line, "{side} first line of stderr");
            let stdout_text = String::from_utf8_lossy(&stdout);
            let first_out = stdout_text.split('\n').next().unwrap();
            assert_eq!(
                first_out, s.stdout_first_line,
                "{side} first line of stdout"
            );
            let out_first_txt =
                fs::read_to_string(run_dir.join(format!("{side}.stdout_first_line.txt"))).unwrap();
            assert_eq!(
                out_first_txt.trim(),
                s.stdout_first_line,
                "{side} stdout_first_line.txt"
            );
            assert_eq!(
                hash_str(&s.stdout_first_line),
                s.stdout_first_line_sha256,
                "{side} stdout first-line hash"
            );
        }

        for id in &cap.residuals {
            assert!(
                store.residual_path(id).unwrap().is_file(),
                "run {} lists missing residual {id}",
                cap.run
            );
        }
        runs += 1;
    }
    assert!(runs >= 1, "at least one court run must be captured");
}

// ---------------------------------------------------------------------------
// objects/ — content-addressed execution snapshots
// ---------------------------------------------------------------------------

#[test]
fn objects_are_content_addressed_and_sealed() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("objects/sha256")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        assert_eq!(name.len(), 64, "object name {name}");
        assert!(name.chars().all(|c| c.is_ascii_hexdigit()));
        // The name MUST be the content: a hand-planted or corrupted object
        // fails here, and the court runner refuses to execute it.
        let bytes = fs::read(&path).unwrap();
        assert_eq!(
            host::sha256_bytes(&bytes),
            name,
            "object {} is not content-addressed (hand-edited?)",
            path.display()
        );
        // (Sealing is a materialization-time property, unit-tested in
        // store.rs: git does not preserve write bits across checkouts, so a
        // cloned tree's modes are not evidence.)
        found += 1;
    }
    assert!(
        found >= 3,
        "the golden path must leave at least three objects (authority, candidate, fixture)"
    );
}

// ---------------------------------------------------------------------------
// residuals/ + tokens
// ---------------------------------------------------------------------------

#[test]
fn residuals_and_tokens_are_self_consistent() {
    let store = store();
    let mut count = 0;
    for entry in fs::read_dir(store.root.join("residuals")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        if name.ends_with(".token.json") || !name.ends_with(".json") {
            continue;
        }
        let r: ResidualRecord = load(&path);
        assert_eq!(r.schema_version, SCHEMA_RESIDUAL, "residual {}", r.id);
        assert_eq!(
            r.id,
            path.file_stem().unwrap().to_string_lossy(),
            "filename must match id"
        );
        assert!(
            r.id.starts_with(&format!("{}-{}", r.kind.domain_prefix(), r.kind.as_str())),
            "id shape for {}",
            r.id
        );
        match r.kind.as_str() {
            "exit" => {
                assert_eq!(r.axis, ObservableId::exit());
                assert_eq!(r.surface, None, "exit residual must not carry a surface");
            }
            "text" => match r.axis.as_str() {
                "stderr" => assert_eq!(
                    r.surface.as_deref(),
                    Some("first-diagnostic-line"),
                    "surface must match the axis"
                ),
                "stdout" => assert_eq!(
                    r.surface.as_deref(),
                    Some("first-stdout-line"),
                    "surface must match the axis"
                ),
                // The domain surfaces (Phase 8): the produced-tree comparator
                // surfaces divergences by path, the JSON comparator by JSON
                // pointer, the byte/wire comparator carries no surface.
                "filesystem.tree" => assert!(
                    r.surface.as_deref().is_some_and(|s| s.starts_with("path:")),
                    "tree residual must be surfaced by path, got {:?}",
                    r.surface
                ),
                "bytes.wire" => assert_eq!(r.surface, None),
                axis => {
                    // structured.state and any externally served axis: the
                    // surface is whatever the comparator declared.
                    assert!(
                        matches!(axis, "structured.state" | "timing.latency"),
                        "text residual on unexpected axis {axis:?}"
                    );
                }
            },
            other => panic!("unexpected residual kind {other:?}"),
        }
        assert_eq!(
            hash_str(&r.raw_reference),
            r.raw_reference_sha256,
            "raw_reference hash"
        );
        assert_eq!(
            hash_str(&r.raw_candidate),
            r.raw_candidate_sha256,
            "raw_candidate hash"
        );
        assert!(
            store.run_dir(&r.run).unwrap().is_dir(),
            "residual {} references missing run {}",
            r.id,
            r.run
        );
        // The observation is bound to the exact candidate artifact that ran.
        let capture = store.load_capture(&r.run).unwrap();
        assert_eq!(
            r.candidate_sha256, capture.candidate_artifact.sha256,
            "residual {} candidate identity must match its run",
            r.id
        );
        // The observation record must never carry a disposition.
        let raw = fs::read_to_string(&path).unwrap();
        assert!(
            !raw.contains("disposition"),
            "observation {} must be immutable (no disposition field)",
            r.id
        );
        // Dispositions live in append-only events; the projection is the
        // last event, and the token follows it.
        let events = store.disposition_events(&r.id).unwrap();
        let disposition = events
            .last()
            .map(|e| e.disposition.clone())
            .unwrap_or(Disposition::Open);
        match &disposition {
            Disposition::Open => assert!(disposition.reason().is_none()),
            Disposition::Closed { reason, .. } => {
                assert!(
                    !reason.trim().is_empty(),
                    "closed residual {} has empty reason",
                    r.id
                );
                assert!(
                    !reason.contains('\n'),
                    "closed residual {} has multi-line reason",
                    r.id
                );
            }
            Disposition::Fixed {
                reason,
                resolution_run_id,
                closure_predicate,
            } => {
                assert!(
                    !reason.trim().is_empty() && !reason.contains('\n'),
                    "fixed residual {} has an invalid reason",
                    r.id
                );
                assert!(
                    !resolution_run_id.is_empty(),
                    "fixed residual {} lacks a resolution run",
                    r.id
                );
                assert!(
                    !closure_predicate.is_empty(),
                    "fixed residual {} lacks a closure predicate",
                    r.id
                );
                // The resolution run must rerun the same question under a
                // compatible envelope and actually close the residual.
                store
                    .resolution_compatibility(&r.run, resolution_run_id, &r.axis)
                    .expect("resolution run must satisfy the comparability predicate");
            }
        }
        // Event sequence numbers are dense and start at 0001; the events are
        // a content-addressed hash chain (each event rederives its own
        // identity, each links to its parent). `disposition_events` already
        // refuses a broken or hand-edited chain; assert the shape explicitly.
        for (i, e) in events.iter().enumerate() {
            assert_eq!(
                e.residual_id, r.id,
                "event {i} of {} has a mismatched residual_id",
                r.id
            );
            assert!(
                e.disposition.as_str() != "open",
                "event {i} of {} is 'open' — events are closures only",
                r.id
            );
            assert_eq!(e.event_id.len(), 64, "event {i} of {} has a bad id", r.id);
            assert_eq!(
                e.parent_event_id,
                if i == 0 {
                    None
                } else {
                    Some(events[i - 1].event_id.clone())
                },
                "event {i} of {} breaks the parent chain",
                r.id
            );
            // The only v0.1.15 evidence a disposition references is the
            // resolution run that closed it.
            match &e.disposition {
                Disposition::Fixed {
                    resolution_run_id, ..
                } => assert_eq!(
                    e.evidence_refs,
                    vec![resolution_run_id.clone()],
                    "event {i} of {} must reference its resolution run",
                    r.id
                ),
                _ => assert!(
                    e.evidence_refs.is_empty(),
                    "event {i} of {} carries unexpected evidence refs",
                    r.id
                ),
            }
        }
        // The token file must be exactly κ(residual, projection).
        let token: TokenRecord = load(&store.token_path(&r.id).unwrap());
        assert_eq!(
            token,
            kappa::kappa(&r, &disposition),
            "token for {} drifted",
            r.id
        );
        count += 1;
    }
    assert!(count >= 2, "the golden path must leave two residuals");
}

// ---------------------------------------------------------------------------
// receipts/
// ---------------------------------------------------------------------------

#[test]
fn receipts_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("receipts")).unwrap() {
        let path = entry.unwrap().path();
        let id = path.file_stem().unwrap().to_string_lossy().to_string();
        let rec: Receipt = load_json(&path);
        assert_eq!(rec.schema_version, SCHEMA_RECEIPT, "receipt {id}");

        // Evidentiary verification: the receipt must be content-addressed,
        // semantically conformant, and derived from its verified capture
        // (court, artifacts, environment, provenance, comparators,
        // observables, residuals, fingerprints, tokens, dispositions,
        // resolution edges) before the tree will treat it as evidence.
        frf::verify::load_receipt_verified(&store, &id)
            .unwrap_or_else(|e| panic!("receipt {id} fails verification: {e}"));

        // The id is content-addressed: receipt-{run}-{full SHA-256 of the
        // canonical (RFC 8785) body bytes}.
        let rest = id
            .strip_prefix("receipt-")
            .unwrap_or_else(|| panic!("bad receipt id {id}"));
        let (run, digest) = rest
            .rsplit_once('-')
            .expect("receipt id must end in the digest");
        assert_eq!(
            digest.len(),
            64,
            "the digest is the full SHA-256, not a prefix"
        );
        assert_eq!(rec.run, run, "receipt {id} run field must match its id");
        assert!(
            store.run_dir(run).unwrap().is_dir(),
            "receipt {id} references missing run {run}"
        );
        let json = canon::canonical(&rec).unwrap();
        assert_eq!(
            host::sha256_bytes(json.as_bytes()),
            digest,
            "receipt {id} is not content-addressed (hand-edited?)"
        );

        // Structured replay block: executing it reproduces the run.
        assert_eq!(rec.replay.program, "frf");
        assert_eq!(rec.replay.expected_run_identity, rec.run);
        assert!(rec.replay.argv.len() >= 5);
        assert_eq!(rec.replay.argv[0], "--root");
        assert_eq!(
            rec.replay.argv[1], "frf",
            "evidence root recorded at capture"
        );
        assert_eq!(rec.replay.argv[2], "court");
        assert_eq!(rec.replay.argv[3], "run");

        // Authority block matches the admitted record.
        let authority: AuthorityRecord = store
            .load_authority(&format!("{}-{}", rec.authority.name, rec.authority.version))
            .unwrap();
        assert_eq!(rec.authority.kind, authority.kind);
        assert_eq!(rec.authority.identity_hash, authority.executable_sha256);
        assert_eq!(
            rec.court.admissibility_envelope.authority_versions,
            vec![authority.version.clone()]
        );

        // Fixture block matches the run.
        let cap = store.load_capture(run).unwrap();
        assert_eq!(rec.fixtures.len(), 1);
        assert_eq!(rec.fixtures[0].id, cap.fixture);
        assert_eq!(rec.fixtures[0].hash, cap.fixture_sha256);
        assert_eq!(rec.fixtures[0].arguments, cap.arguments);
        assert_eq!(
            rec.fixtures[0].declared_arguments, cap.court_spec.fixture.arguments,
            "the declared arguments are the semantic identity's input"
        );

        // Runner + comparator semantics + environment are copied from the
        // capture (bound at observation time), never reconstructed at emit
        // time.
        assert_eq!(rec.provenance, cap.provenance);
        assert_eq!(rec.comparator_semantics, cap.comparator_semantics);
        assert_eq!(rec.environment, cap.environment);
        assert_eq!(rec.court.semantic_identity, cap.court_semantic_identity);
        assert_eq!(
            rec.authority.interpreter,
            cap.authority_artifact.interpreter
        );
        assert_eq!(rec.candidate.identity_hash, cap.candidate_artifact.sha256);
        assert_eq!(
            rec.candidate.interpreter,
            cap.candidate_artifact.interpreter
        );

        // Observables are consistent with the residuals on each axis.
        let family = &rec.court.admissibility_envelope.fixture_family;
        for obs in &rec.observables {
            assert!(
                rec.court
                    .admissibility_envelope
                    .observables
                    .contains(&obs.axis),
                "undecared axis {} in receipt",
                obs.axis
            );
            let has_residual = rec.residuals.iter().any(|r| r.axis == obs.axis);
            match obs.verdict {
                ObservableVerdict::Pass => {
                    assert!(!has_residual, "pass verdict with residual on {}", obs.axis)
                }
                ObservableVerdict::Residual => assert!(
                    has_residual,
                    "residual verdict without residual on {}",
                    obs.axis
                ),
            }
            assert!(rec.residuals.iter().all(|r| r.axis != obs.axis || {
                let implementation = cap
                    .provenance
                    .comparator_implementations
                    .iter()
                    .find(|i| i.id == obs.axis)
                    .unwrap();
                let (ref_h, cand_h, req, res_) = match &implementation.artifact {
                    None => {
                        let builtin = frf::comparators::BuiltinKind::from_id(&obs.axis).unwrap();
                        let (ref_h, cand_h) = match builtin {
                            frf::comparators::BuiltinKind::Exit => (
                                cap.reference.exit_sha256.clone(),
                                cap.candidate.exit_sha256.clone(),
                            ),
                            frf::comparators::BuiltinKind::Stderr => (
                                cap.reference.stderr_first_line_sha256.clone(),
                                cap.candidate.stderr_first_line_sha256.clone(),
                            ),
                            frf::comparators::BuiltinKind::Stdout => (
                                cap.reference.stdout_first_line_sha256.clone(),
                                cap.candidate.stdout_first_line_sha256.clone(),
                            ),
                            frf::comparators::BuiltinKind::Tree => (
                                cap.reference
                                    .produced
                                    .as_ref()
                                    .map(|p| p.manifest_sha256.clone())
                                    .unwrap_or_default(),
                                cap.candidate
                                    .produced
                                    .as_ref()
                                    .map(|p| p.manifest_sha256.clone())
                                    .unwrap_or_default(),
                            ),
                            frf::comparators::BuiltinKind::Bytes
                            | frf::comparators::BuiltinKind::Json => (
                                cap.reference.stdout_sha256.clone(),
                                cap.candidate.stdout_sha256.clone(),
                            ),
                        };
                        (ref_h, cand_h, None, None)
                    }
                    Some(_) => {
                        let evidence = store.load_comparator_evidence(run, &obs.axis).unwrap();
                        let dir = store.comparator_dir(run, &obs.axis).unwrap();
                        let request_value = frf::canon::parse_strict(
                            &std::fs::read(dir.join("request.json")).unwrap(),
                        )
                        .unwrap();
                        let ref_h = frf::host::sha256_bytes(
                            frf::canon::encode(&request_value["reference"])
                                .unwrap()
                                .as_bytes(),
                        );
                        let cand_h = frf::host::sha256_bytes(
                            frf::canon::encode(&request_value["candidate"])
                                .unwrap()
                                .as_bytes(),
                        );
                        (
                            ref_h,
                            cand_h,
                            Some(evidence.invocation.request_cid.clone()),
                            Some(evidence.result.result_id.clone()),
                        )
                    }
                };
                obs.raw_reference_hash == ref_h
                    && obs.raw_candidate_hash == cand_h
                    && obs.comparator_request == req
                    && obs.comparator_result == res_
            }));
            // The residual's kind must be its comparator's classifier.
            for r in rec.residuals.iter().filter(|r| r.axis == obs.axis) {
                let classifier = rec
                    .comparator_semantics
                    .iter()
                    .find(|s| s.id == obs.axis)
                    .unwrap()
                    .residual_classifier
                    .clone();
                assert_eq!(
                    r.kind.as_str(),
                    classifier,
                    "residual kind must be the axis's residual classifier"
                );
            }
        }

        // Every residual entry re-derives from its file.
        for res in &rec.residuals {
            let record = store.load_residual(&res.id).unwrap();
            assert_eq!(res.axis, record.axis.as_str());
            assert_eq!(res.kind, record.kind);
            assert_eq!(res.raw_reference_hash, record.raw_reference_sha256);
            assert_eq!(res.raw_candidate_hash, record.raw_candidate_sha256);
            assert_eq!(
                res.grammar_state,
                kappa::grammar_state(&disposition_from_receipt(res)),
                "grammar_state for {}",
                res.id
            );
            assert_eq!(
                res.residual_fingerprint,
                residual_fingerprint(&record),
                "fingerprint for {}",
                res.id
            );
            // A residual reproduces by replaying the run that observed it.
            assert_eq!(res.reproducer, rec.run);
            assert!(res.invariant.is_empty(), "v0 has no invariants");
            // The sign verifies against the evidence it PINNED: every
            // trajectory-evidence entry names the exact ExecutionSeries
            // snapshot the drift/slew were derived from (replayed by the
            // verifier). An empty entry list is a single-run snapshot of emit
            // time — a later experiment referencing the same run does not
            // rewrite a receipt.
            let record = store.load_residual(&res.id).unwrap();
            frf::verify::verify_sign(&store, &record, &res.sign)
                .unwrap_or_else(|e| panic!("sign of {} fails pinned verification: {e}", res.id));
            let mut seen_coordinate_systems: Vec<&str> = Vec::new();
            for entry in &res.sign.trajectory_evidence {
                assert!(
                    frf::model::TrajectoryDrift::parse(&entry.drift).is_some(),
                    "invalid drift {:?} for {}",
                    entry.drift,
                    res.id
                );
                assert!(
                    frf::model::TrajectorySlew::parse(&entry.slew).is_some(),
                    "invalid slew {:?} for {}",
                    entry.slew,
                    res.id
                );
                assert!(
                    !seen_coordinate_systems.contains(&entry.coordinate_system.as_str()),
                    "duplicate coordinate system {} in the sign of {}",
                    entry.coordinate_system,
                    res.id
                );
                seen_coordinate_systems.push(&entry.coordinate_system);
            }
            if res.disposition == "fixed" {
                // Receipts are snapshots: the resolution edge is bound only
                // for entries that were fixed at emit time, and it must match
                // the projected disposition (the last event).
                let projected = store.current_disposition(&res.id).unwrap();
                assert_eq!(
                    res.resolution_run_id,
                    projected.resolution_run_id().map(str::to_string),
                    "resolution edge for {} drifted",
                    res.id
                );
                assert_eq!(
                    res.closure_predicate.as_deref(),
                    match &projected {
                        Disposition::Fixed {
                            closure_predicate, ..
                        } => Some(closure_predicate.as_str()),
                        _ => None,
                    },
                    "closure predicate for {} drifted",
                    res.id
                );
            } else {
                assert!(
                    res.resolution_run_id.is_none() && res.closure_predicate.is_none(),
                    "non-fixed entry {} carries a resolution_run_id or closure_predicate",
                    res.id
                );
            }
            // The receipt binds the EXACT content-addressed event that
            // supplied this disposition: a non-open entry must name an event
            // in the residual's hash chain, an open entry must name none
            // (open is the projection of no events). The verified loader
            // additionally proves the bound event's fields match exactly.
            match &res.disposition_event_id {
                Some(eid) => {
                    assert!(
                        res.disposition != "open",
                        "open entry {} carries a disposition_event_id",
                        res.id
                    );
                    let events = store.disposition_events(&res.id).unwrap();
                    assert!(
                        events.iter().any(|e| &e.event_id == eid),
                        "entry {} binds event {eid} which is not in its chain",
                        res.id
                    );
                }
                None => assert_eq!(
                    res.disposition, "open",
                    "entry {} has disposition {} without a bound event",
                    res.id, res.disposition
                ),
            }
        }

        // Endoduction tokens re-derive from κ over the residual *as this
        // receipt saw it*: the raw fields from the file (immutable), the
        // disposition from the receipt (a snapshot, since receipts bind the
        // state at emit time).
        assert_eq!(rec.endoduction.schema_version, TOKEN_SCHEMA_VERSION);
        assert_eq!(rec.endoduction.tokens.len(), rec.residuals.len());
        for (res, token) in rec.residuals.iter().zip(&rec.endoduction.tokens) {
            let seen = store.load_residual(&res.id).unwrap();
            let disposition = disposition_from_receipt(res);
            let k = kappa::kappa(&seen, &disposition);
            assert_eq!(token.residual_id, res.id);
            assert_eq!(token.token, k.token, "token for {}", res.id);
            assert_eq!(token.next_court, k.next_court);
            assert_eq!(token.blocks_claims, k.blocks_claims);
        }

        // Claim section is what the compiler would emit at this state.
        assert!(
            rec.claims.positive.is_empty(),
            "v0 receipts carry no positive claims"
        );
        assert_eq!(rec.claims.non_claims, sentences::non_claims(family));
        assert_eq!(
            rec.claims.blocked_by_open_residuals,
            sentences::refusal_lines_from_residuals(&rec.residuals, family)
        );
        found += 1;
    }
    assert!(
        found >= 2,
        "the golden path must leave two receipts (open + final)"
    );
}

// ---------------------------------------------------------------------------
// trajectories/ — residual trajectories over a coordinate system
// ---------------------------------------------------------------------------

#[test]
fn trajectories_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("trajectories")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let t: TrajectoryRecord = load(&path);
        assert_eq!(t.schema_version, SCHEMA_TRAJECTORY, "trajectory {name}");
        // The filename is {lineage}.{coordinate_system}.{series}.json and
        // MUST match the record.
        assert_eq!(
            name,
            format!("{}.{}.{}.json", t.subject, t.coordinate_system, t.series),
            "the filename must be lineage.coordinate-system.series"
        );
        assert_eq!(t.subject.len(), 64, "subject must be a lineage digest");
        assert!([
            "repeat_index",
            "candidate_revision",
            "authority_version",
            "environment",
            "time"
        ]
        .contains(&t.coordinate_system.as_str()));
        assert!(matches!(t.axis.as_str(), "exit" | "stderr" | "stdout"));

        // The series snapshot it derives from exists, matches the experiment,
        // and contains every observation's run.
        let series = store.load_series(&t.series).unwrap();
        assert_eq!(series.court, "cli-malformed-input");
        assert_eq!(series.coordinate_system, t.coordinate_system);
        assert_eq!(series.points.len(), t.observations.len());
        for (i, o) in t.observations.iter().enumerate() {
            assert_eq!(o.point_index, series.points[i].point_index);
            assert_eq!(o.coordinate, series.points[i].coordinate);
            assert_eq!(o.run, series.points[i].run);
            assert!(
                store.run_dir(&o.run).unwrap().is_dir(),
                "observation {} run {} missing",
                o.point_index,
                o.run
            );
            if o.observed {
                let id = o
                    .residual
                    .as_deref()
                    .expect("an observed entry must name the residual");
                let rec = store.load_residual(id).unwrap();
                assert_eq!(
                    rec.run, o.run,
                    "observation residual must belong to its run"
                );
                let lineage = frf::semantics::residual_lineage_of_record(&store, &rec).unwrap();
                assert_eq!(
                    lineage, t.subject,
                    "observation residual must carry the subject lineage"
                );
                assert_eq!(
                    frf::semantics::residual_fingerprint(&rec).unwrap(),
                    o.fingerprint
                        .as_deref()
                        .expect("observed entry has a fingerprint"),
                    "observation fingerprint must match the residual"
                );
                // The magnitude REDERIVES from the observed residual's
                // compared projections (the declared measure); it is never
                // trusted from the trajectory file.
                let expected_mag = frf::comparators::divergence_magnitude(
                    rec.axis.as_str(),
                    &rec.raw_reference,
                    &rec.raw_candidate,
                );
                assert_eq!(
                    o.magnitude, expected_mag,
                    "observation magnitude must rederive from the residual"
                );
                assert_eq!(rec.axis.as_str(), t.axis);
            } else {
                assert!(
                    o.residual.is_none() && o.fingerprint.is_none() && o.magnitude.is_none(),
                    "an unobserved entry names no residual"
                );
            }
        }
        let observed: Vec<bool> = t.observations.iter().map(|o| o.observed).collect();
        assert!(
            observed.iter().any(|o| *o),
            "a trajectory only exists for an observed divergence"
        );
        // The derivation is the deterministic classification of the pattern
        // over the coordinate system with the rederived magnitudes — trend
        // and magnitude_kind included.
        let magnitudes: Vec<Option<String>> = t
            .observations
            .iter()
            .map(|o| {
                o.residual.as_ref().and_then(|rid| {
                    let rec = store.load_residual(rid).unwrap();
                    frf::comparators::divergence_magnitude(
                        rec.axis.as_str(),
                        &rec.raw_reference,
                        &rec.raw_candidate,
                    )
                })
            })
            .collect();
        let kind = frf::comparators::magnitude_kind(&t.axis);
        let expected =
            frf::trajectory::classify(&observed, &t.coordinate_system, &magnitudes, &kind).unwrap();
        assert_eq!(t.derivation, expected, "derivation must rederive");
        found += 1;
    }
    assert!(
        found >= 1,
        "the golden path must leave at least one trajectory"
    );
}

#[test]
fn series_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("series")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        assert!(name.ends_with(".json"), "series file name: {name}");
        let id = name.trim_end_matches(".json").to_string();
        let series: ExecutionSeries = load(&path);
        assert_eq!(series.schema_version, SCHEMA_SERIES, "series {name}");
        assert_eq!(
            series.id, id,
            "the filename must be the series content address"
        );
        // The content address rederives.
        assert_eq!(
            frf::semantics::series_identity(
                &series.experiment_id,
                series.parent_series_id.as_deref(),
                &series.court,
                &series.coordinate_system,
                &series.points
            )
            .unwrap(),
            series.id
        );
        assert_eq!(
            series.experiment_id,
            format!("{}-{}", series.court, series.coordinate_system)
        );
        assert!([
            "repeat_index",
            "candidate_revision",
            "authority_version",
            "environment",
            "time"
        ]
        .contains(&series.coordinate_system.as_str()));
        // Every parent link resolves to a series of the SAME experiment, and
        // the chain contains the parent's points as a prefix (an append only
        // extends).
        if let Some(parent_id) = &series.parent_series_id {
            let parent = store.load_series(parent_id).unwrap();
            assert_eq!(parent.experiment_id, series.experiment_id);
            assert!(
                parent.points.len() <= series.points.len(),
                "a series append must not shrink the experiment"
            );
        }
        // Points are dense, ordered, and reference existing runs.
        for (i, p) in series.points.iter().enumerate() {
            assert_eq!(p.point_index, (i + 1).to_string(), "dense point series");
            assert!(
                store.run_dir(&p.run).unwrap().is_dir(),
                "series point {} run {} missing",
                p.point_index,
                p.run
            );
        }
        found += 1;
    }
    assert!(found >= 1, "the golden path must leave at least one series");
}

// ---------------------------------------------------------------------------
// witnesses/ — independent attestations
// ---------------------------------------------------------------------------

#[test]
fn witness_statements_are_self_consistent() {
    let store = store();
    let dir = store.root.join("witnesses");
    let mut found = 0;
    if !dir.is_dir() {
        return;
    }
    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        // The preserved request/response evidence lives under
        // `witnesses/<id>/` (a directory); the STATEMENT is the `<id>.json`
        // file (canonical JSON, like receipts).
        if path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        if !name.ends_with(".json") {
            continue;
        }
        let id = name.trim_end_matches(".json").to_string();
        // The verified loader rehashes everything: the identity rederives,
        // the preserved request/response hash to their cids, the response
        // names its request, and the attestation names the statement.
        let stmt = store.load_witness_statement(&id).unwrap();
        assert_eq!(stmt.id, id, "the filename must be the content address");
        // v3: the witness IDENTITY (the stable WHO) rederives from the
        // relation's specification and the program's bytes + interpreter.
        assert_eq!(
            frf::semantics::witness_identity(&stmt.witness_semantic, &stmt.witness_implementation)
                .unwrap(),
            stmt.witness_identity,
            "the witness identity must rederive"
        );
        if let Some(authority) = &stmt.authority {
            assert!(
                frf::model::WitnessAuthority::KINDS.contains(&authority.kind.as_str()),
                "declared authority kind is closed"
            );
        }
        assert!(
            matches!(stmt.subject.kind.as_str(), "run" | "receipt" | "residual"),
            "witness subject kind"
        );
        // The subject content address rederives from the evidence object.
        match stmt.subject.kind.as_str() {
            "residual" => {
                let record = store.load_residual(&stmt.subject.id).unwrap();
                assert_eq!(
                    stmt.subject.cid,
                    frf::semantics::residual_fingerprint(&record).unwrap()
                );
            }
            "run" => {
                let verified =
                    frf::verify::load_capture_verified(&store, &stmt.subject.id).unwrap();
                let residuals: Vec<ResidualRecord> = verified
                    .capture
                    .residuals
                    .iter()
                    .map(|rid| store.load_residual(rid).unwrap())
                    .collect();
                assert_eq!(stmt.subject.cid, verified.digest(&residuals).unwrap());
            }
            _ => {}
        }
        assert_eq!(stmt.attestation.outcome, "affirm");
        assert_eq!(stmt.attestation.statement, stmt.statement);
        found += 1;
    }
    assert!(
        found >= 1,
        "the golden path must leave at least one witness statement"
    );
}

/// independence/ — the DECLARED independence relations (spec/witness.md §6):
/// every record rederives its identity, binds a verified witness statement,
/// and carries the statement's witness identity + subject verbatim.
#[test]
fn independence_records_are_self_consistent() {
    let store = store();
    let dir = store.root.join("independence");
    let mut found = 0;
    if !dir.is_dir() {
        return;
    }
    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let id = name.trim_end_matches(".json").to_string();
        // The verified loader rehashes: identity rederives, the bound
        // statement verifies, witness identity + subject match the statement.
        let rec = store.load_independence(&id).unwrap();
        assert_eq!(rec.id, id);
        assert!(
            frf::model::INDEPENDENCE_RELATIONS.contains(&rec.relation.as_str()),
            "the relation is closed"
        );
        assert_eq!(
            frf::semantics::independence_specification_hash(&rec.relation, &rec.relation_version)
                .unwrap(),
            rec.specification_hash,
            "the independence spec hash must rederive"
        );
        assert!(!rec.basis.trim().is_empty(), "a basis is mandatory");
        found += 1;
    }
    assert!(
        found >= 1,
        "the golden path must leave at least one independence record"
    );
}

// ---------------------------------------------------------------------------
// reductions/ — minimization experiments
// ---------------------------------------------------------------------------

#[test]
fn reductions_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("reductions")).unwrap() {
        let path = entry.unwrap().path();
        // The external minimizer's invocation evidence lives under
        // `reductions/<id>/minimizer/` (a directory); the RECORD is the
        // `<id>.json` file.
        if path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let id = name.trim_end_matches(".json").to_string();
        let r: ReductionRecord = load(&path);
        assert_eq!(r.schema_version, SCHEMA_REDUCTION, "reduction {name}");
        assert_eq!(r.id, id, "the filename must be the content address");
        // The content address rederives.
        assert_eq!(
            frf::semantics::reduction_identity(
                &r.residual_id,
                &r.source_run,
                &r.axis,
                r.kind.clone(),
                &r.court_semantic_identity,
                &r.authority_artifact_sha256,
                &r.candidate_artifact_sha256,
                &r.environment_digest,
                &r.comparator_semantic_id,
                &r.comparator_semantic_hash,
                &r.comparator_implementation_hash,
                &r.argv_template,
                &r.original_fixture_sha256,
                &r.final_fixture_sha256,
                &r.attempts,
                &r.derivation,
                &r.transform,
                frf::store::minimizer_binding(&r).as_ref().map(|b| {
                    (
                        b.0.as_str(),
                        b.1.as_str(),
                        b.2.as_str(),
                        b.3,
                        b.4.as_str(),
                        b.5.as_str(),
                    )
                }),
            )
            .unwrap(),
            r.id
        );
        // The bound identities match the residual's run's capture: the
        // reduction held the candidate, authority, environment, and
        // comparator fixed — and the record proves it by binding them.
        let capture = store.load_capture(&r.source_run).unwrap();
        assert_eq!(r.court_semantic_identity, capture.court_semantic_identity);
        assert_eq!(
            r.authority_artifact_sha256,
            capture.authority_artifact.sha256
        );
        assert_eq!(
            r.candidate_artifact_sha256,
            capture.candidate_artifact.sha256
        );
        assert_eq!(r.environment_digest, capture.environment.digest);
        assert!(capture
            .comparator_semantics
            .iter()
            .any(|s| s.id == r.comparator_semantic_id
                && s.specification_hash == r.comparator_semantic_hash));
        assert!(capture
            .provenance
            .comparator_implementations
            .iter()
            .any(|i| i.id == r.comparator_semantic_id
                && i.implementation_hash == r.comparator_implementation_hash));
        // The transform declares the reduction's frame.
        assert_eq!(r.transform.kind, "reduction");
        assert_eq!(r.transform.varying_dimensions, vec!["fixture"]);
        assert_eq!(r.transform.success_predicate, "lineage-survives");
        // The referenced artifacts exist (content-addressed).
        for sha in [&r.original_fixture_sha256, &r.final_fixture_sha256] {
            assert!(
                store.object_path(sha).unwrap().is_file(),
                "reduction {id}: object {sha} missing"
            );
        }
        // The residual it minimizes exists, belongs to the source run, and is
        // on the same axis/kind.
        let record = store.load_residual(&r.residual_id).unwrap();
        assert_eq!(record.run, r.source_run);
        assert_eq!(record.axis.as_str(), r.axis);
        assert_eq!(record.kind, r.kind);
        assert_eq!(record.candidate_sha256, r.candidate_artifact_sha256);
        // The final reproducer is genuinely smaller or equal, and every
        // attempt recorded a fixture that exists. Attempts are numbered in
        // order, and only candidates that were preserved AND shrank (or the
        // final verification) are accepted.
        assert!(r.derivation.final_lines <= r.derivation.original_lines);
        assert!(!r.attempts.is_empty());
        assert_eq!(
            r.attempts[0].role,
            frf::model::ReductionAttemptRole::Baseline
        );
        assert!(!r.attempts[0].accepted, "a baseline is never accepted");
        assert!(matches!(
            r.attempts.last().unwrap().role,
            frf::model::ReductionAttemptRole::FinalVerification
        ));
        assert!(r.attempts.last().unwrap().accepted);
        for a in &r.attempts {
            assert!(
                store.object_path(&a.fixture_sha256).unwrap().is_file(),
                "reduction {id}: attempt {} fixture missing",
                a.attempt
            );
        }
        // A minimality-proven reduction is exactly the deterministic ddmin
        // outcome; the budget-cut case must say so honestly.
        assert_eq!(r.derivation.minimality.kind, "one-minimal");
        assert_eq!(r.derivation.minimality.granularity, "line");
        if r.derivation.minimality.proven {
            assert!(
                r.attempts.len() < 256,
                "reduction {id}: minimality proven but the attempt budget was exhausted"
            );
        }
        found += 1;
    }
    assert!(
        found >= 1,
        "the golden path must leave at least one reduction"
    );
}

// ---------------------------------------------------------------------------
// challenges/ — the negative-control evidence (courts that prove they can see)
// ---------------------------------------------------------------------------

#[test]
fn challenges_are_self_consistent() {
    let store = store();
    let mut found = 0;
    for entry in fs::read_dir(store.root.join("challenges")).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let id = name.trim_end_matches(".json").to_string();
        // The verified loader: the content address must rederive from the
        // record's own declared fields (a hand-edited challenge is refused).
        let r: CourtChallenge = store.load_challenge(&id).unwrap();
        assert_eq!(r.schema_version, SCHEMA_CHALLENGE, "challenge {name}");
        assert_eq!(r.id, id, "the filename must be the content address");

        // The mutant artifact rederives: for a built-in operator it is the
        // deterministic wrapper from (operator, reference hash); for an
        // external mutation provider it is the PROPOSED artifact preserved in
        // the response evidence (rehashed here, cross-verified by the
        // loader). Either way the recorded hash is a claim until recomputed.
        match frf::mutation::MutationOperator::parse(&r.operator) {
            Ok(operator) => {
                assert_eq!(operator.target_axis(), r.target_axis);
                let wrapper = operator.wrapper(&r.reference_sha256);
                assert_eq!(
                    host::sha256_bytes(wrapper.as_bytes()),
                    r.mutant_candidate_sha256,
                    "challenge {id}: the mutant artifact must be the deterministic wrapper of the reference"
                );
            }
            Err(_) => {
                // An external mutation provider: the preserved response
                // proposed the mutant; its bytes must rehash to the recorded
                // mutant hash, and the evidence chain must cross-verify.
                assert!(
                    r.mutation_invocation_id.is_some() && r.mutation_result_id.is_some(),
                    "challenge {id}: an external-mutation challenge must bind its evidence"
                );
                let evidence = store.load_mutation_evidence(&id).unwrap();
                assert_eq!(
                    evidence.result.mutant_sha256, r.mutant_candidate_sha256,
                    "challenge {id}: the proposed mutant must rehash to the recorded mutant hash"
                );
                assert_eq!(evidence.invocation.operator, r.operator);
                assert_eq!(evidence.invocation.target_axis, r.target_axis);
                assert_eq!(evidence.result.outcome, "proposed");
            }
        }
        // The reference object exists (content-addressed) and the mutant
        // object exists in the store.
        assert!(store.object_path(&r.reference_sha256).unwrap().is_file());
        assert!(store
            .object_path(&r.mutant_candidate_sha256)
            .unwrap()
            .is_file());

        // The mutant run exists and its residuals are EXACTLY the recorded
        // ones; the derived verdicts recompute from the run — never trusted
        // from the file.
        let capture = store.load_capture(&r.run).unwrap();
        assert_eq!(
            capture.residuals, r.observed_residuals,
            "challenge {id}: the run's residuals must match the record"
        );
        let mut on_target = false;
        let mut on_unaffected: Vec<String> = Vec::new();
        for rid in &r.observed_residuals {
            let record = store.load_residual(rid).unwrap();
            if record.axis.as_str() == r.target_axis {
                on_target = true;
            } else {
                on_unaffected.push(record.axis.as_str().to_string());
            }
        }
        assert_eq!(
            on_target, r.saw_defect,
            "challenge {id}: saw_defect must rederive from the run's residuals"
        );
        assert_eq!(
            on_unaffected.is_empty(),
            r.specificity_clean,
            "challenge {id}: specificity_clean must rederive from the run's residuals"
        );
        // The unaffected axes are the declared observables minus the target.
        let declared: Vec<String> = capture
            .court_spec
            .admissibility_envelope
            .observables
            .iter()
            .filter(|o| *o != &r.target_axis)
            .cloned()
            .collect();
        assert_eq!(r.unaffected_axes, declared);

        // A challenge record must prove its court can see: the verdicts are
        // the point of the object.
        assert!(
            r.saw_defect && r.specificity_clean,
            "challenge {id}: the checked-in golden path must not contain a blind court"
        );
        found += 1;
    }
    assert!(
        found >= 1,
        "the golden path must leave at least one court challenge"
    );
}

// ---------------------------------------------------------------------------
// claims/
// ---------------------------------------------------------------------------

#[test]
fn claims_are_re_derivable_from_receipts() {
    let store = store();
    let claims_dir = store.root.join("claims");
    let mut names: Vec<String> = fs::read_dir(&claims_dir)
        .unwrap()
        .flatten()
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".json"))
        .collect();
    names.sort();
    let mut found = 0;
    for name in names {
        let claim_id = name.trim_end_matches(".json").to_string();
        // The claim VERIFIES as a whole — identity rederives (FRF/CLAIM/v1
        // over the canonical document minus the id), every premise is a
        // verified receipt, subject coherence holds, K rederives and is
        // contained in P, the knowledge universe rederives from the store,
        // the blocker search over the COMMITTED U is empty, the policy
        // evidence (capability / witness / independence / replay contract)
        // re-verifies, and the derived projections rederive. This is the
        // same gate `frf claim render` applies — a hand-written canonical
        // claim file is refused here.
        let verified = frf::verify::load_claim_verified(&store, &claim_id)
            .unwrap_or_else(|e| panic!("claim {claim_id} fails verification: {e}"));
        let claim = verified.claim();
        assert_eq!(claim.schema_version, SCHEMA_CLAIM);
        let receipt_id = claim.receipt.clone();
        let rec = verified.premises()[0].body();
        let family = &rec.court.admissibility_envelope.fixture_family;

        // The prose is DERIVED, never stored as authoritative Claim IR: the
        // render view derives the positive sentence and the non-claims from
        // the VERIFIED premises.
        let view = frf::render::RenderView::from_verified(&verified).unwrap();
        assert_eq!(
            view.positive,
            vec![sentences::positive_claim(rec).expect("claimable receipt")],
            "claim {claim_id}: the derived prose drifted from its receipt"
        );
        assert_eq!(view.non_claims, sentences::non_claims(family));

        // The by-receipt index binds the claim to its root receipt. v8
        // semantics: the same receipt compiled under a different universe or
        // policy is a DIFFERENT claim, and they coexist — the index is a
        // non-normative directory over immutable claim objects, so the check
        // is membership, not a singleton.
        assert!(
            store
                .claim_index_path(&receipt_id, &claim_id)
                .unwrap()
                .is_file(),
            "claim {claim_id} is missing from the by-receipt index"
        );
        let bound = store.claim_ids_for_receipt(&receipt_id).unwrap();
        assert!(
            bound.contains(&claim_id),
            "claim {claim_id} is not bound to receipt {receipt_id} in the by-receipt index (found {bound:?})"
        );

        // The claimed receipt reflects the current residual dispositions.
        for res in &rec.residuals {
            let projected = store.current_disposition(&res.id).unwrap();
            assert_eq!(
                res.disposition,
                projected.as_str(),
                "receipt {receipt_id} disposition for {} is stale",
                res.id
            );
        }

        // The claim is attributed to the EXACT candidate artifact the
        // receipt's run executed: the identity hash must equal the run's
        // captured candidate bytes, never a label.
        let rest = receipt_id
            .strip_prefix("receipt-")
            .unwrap_or_else(|| panic!("bad receipt id {receipt_id}"));
        let (run, _) = rest
            .rsplit_once('-')
            .expect("receipt id must end in the digest");
        let cap = store.load_capture(run).unwrap();
        assert_eq!(
            claim.candidate.identity_hash, cap.candidate_artifact.sha256,
            "claim {claim_id} is attributed to a candidate artifact the run did not execute"
        );
        found += 1;
    }
    assert!(found >= 1, "at least one compiled claim must exist");
}

// ---------------------------------------------------------------------------
// layout
// ---------------------------------------------------------------------------

#[test]
fn tree_mirrors_section_19_3() {
    let store = store();
    for sub in [
        "authorities",
        "courts",
        "captures",
        "objects",
        "residuals",
        "series",
        "trajectories",
        "reductions",
        "receipts",
        "claims",
    ] {
        assert!(
            store.root.join(sub).is_dir(),
            "missing {sub}/ in the evidence tree"
        );
    }
    assert!(store
        .root
        .join("courts/cli-malformed-input/manifest.yaml")
        .is_file());
    assert!(store
        .root
        .join("courts/cli-malformed-input/fixtures/malformed-path.conf")
        .is_file());
    // No stray non-JSON droppings in the generated directories: generated
    // evidence is canonical JSON; YAML is only human-authored manifests. The
    // claims/ by-receipt INDEX is the one declared subdirectory.
    for sub in ["authorities", "receipts"] {
        for entry in fs::read_dir(store.root.join(sub)).unwrap() {
            let name = entry.unwrap().file_name().to_string_lossy().to_string();
            assert!(name.ends_with(".json"), "unexpected file {sub}/{name}");
        }
    }
    let claims_dir = store.root.join("claims");
    for entry in fs::read_dir(&claims_dir).unwrap() {
        let name = entry.unwrap().file_name().to_string_lossy().to_string();
        assert!(
            name.ends_with(".json") || name == "by-receipt",
            "unexpected file claims/{name}"
        );
    }
}
